### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGridNetwork#23]
## Description
We need to rename this project slightly to fit [our new project naming standards](https://github.com/OpenMined/.github/issues/11).

**The new name for this repo should be:** PyGridNetwork
**The new release name for this repo should be:** openmined.gridnetwork

I have gone ahead and renamed the repo, but I will need someone else to be in charge of changing the release name. **With that said, if this repo doesn't have an official release, then this issue can be closed.**

If you have any questions about this issue, please comment here or message **@cereallarceny** on Slack.

**Comment by IonesioJunior** [comment]
@Benardi

**Comment by Benardi** [comment]
@cereallarceny when you say "a new release name", do you refer solely to the release notes or to the package name as well (what will be shown in PyPi) ?

If you also refer to the package name  as  "openmined.gridNetwork" you mean "gridNetwork" or literally "openmined.gridNetwork" ?

**Comment by cereallarceny** [comment]
I mean the package name that is released to PyPi. And yes, it would be
openmined.gridNetwork. This is a practice called “org scoping” that we’re
going to start following as an organization.

**Comment by Benardi** [comment]
# About "gridNetwork"

The usage of CamelCase for a module/package is not the Python norm and is discouraged by the community via the [PEP 8 Style guide](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) . 
Taking in consideration the recommendation of making everything lowercase and using underscores names I believe that names like `gridnetwork` or `grid_network`  would conform to PEP.



# About the "organization.projectname"

Because of the way Python works  a package can't have a dot in its name. When you import "X.Y" the interpreter first looks for  "X" in its namespace.

* A name like "organization_projectname" would work for a python package.

**Comment by cereallarceny** [comment]
Dot-separating by org scoping is actually the suggested standard for the Python community. https://www.python.org/dev/peps/pep-0423/#top-level-namespace-relates-to-code-ownership

**Comment by Benardi** [comment]
> Dot-separating by org scoping is actually the suggested standard for the Python community. https://www.python.org/dev/peps/pep-0423/#top-level-namespace-relates-to-code-ownership

Most of the examples in [pep-0423](https://www.python.org/dev/peps/pep-0423/#top-level-namespace-relates-to-code-ownership)  subscribe to `snakecase` over `camelcase`.
Wouldn't   **openmined.gridnetwork** respect both [pep-0423](https://www.python.org/dev/peps/pep-0423/#top-level-namespace-relates-to-code-ownership) and [pep-0008](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) ?

**Comment by cereallarceny** [comment]
Updated the above issue description to appease @Benardi and making the appropriate changes for all other issues related to Python repos.
